services:
  - type: web
    name: ecobio
    env: python
    plan: free
    branch: main   # ðŸ‘ˆ tu rama principal
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
